### ISSUE TITLE
[Connector Roadmap] Create Tile Component

### ISSUE THREAD

**Issue by jayjayjpg** [ConduitIO/mx-ui-components#29]
As part of the Connector Roadmap feature, we should create a reusable tile component that can be used on the Resource Catalog page.

Ideally, both the tile body, as well as the call-to-action section should be easily configurable (for example via named blocks).

### Technical suggestions

- [ ] generate a new `Mox::` component for the tile UI via `ember generate component...`
- [ ] use named blocks or a similar approach to make the component easy to reuse
- [ ] add at least one Storybook story displaying the component
- [ ] add at least one integration test verifying the correct display of the component
- [ ] add at least one integration test verifying that whenever the user clicks the CTA section, the associated action is triggered

**Comment by jayjayjpg** [comment]
This can be closed since we decied to [reuse existing components for the tile layout instead](https://meroxa.slack.com/archives/C03FL181C3A/p1674653513762239)
